package com.deeshank.models;

// default package
// Generated Apr 27, 2015 7:51:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books", catalog = "inventory", uniqueConstraints = @UniqueConstraint(columnNames = "barcode"))
public class Books implements java.io.Serializable {

	private Integer id;
	private int barcode;
	private String title;
	private String author;
	private Integer noOfPgs;

	public Books() {
	}

	public Books(int barcode, String title) {
		this.barcode = barcode;
		this.title = title;
	}

	public Books(int barcode, String title, String author, Integer noOfPgs) {
		this.barcode = barcode;
		this.title = title;
		this.author = author;
		this.noOfPgs = noOfPgs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "barcode", unique = true, nullable = false)
	public int getBarcode() {
		return this.barcode;
	}

	public void setBarcode(int barcode) {
		this.barcode = barcode;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "author", length = 100)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "no_of_pgs")
	public Integer getNoOfPgs() {
		return this.noOfPgs;
	}

	public void setNoOfPgs(Integer noOfPgs) {
		this.noOfPgs = noOfPgs;
	}

}
